#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 19 16:29:41 2020

@author: davidy
"""
import numpy as np
import matplotlib.pyplot as plt
from scipy.fftpack import dct as dct
from scipy.fftpack import idct as idct
from numpy.polynomial.chebyshev import chebval as chebval
from scipy.special import eval_chebyt as chebyt
from fwing import fct as fct
from fwing import algorithm1 as algorithm1
from fwing import ifct as ifct
from fwing import cheb_diff as cheb_diff

N = 100
n = np.arange(0,N,1)
theta = np.pi*(2*n+1)/((2*(N)))
x = np.cos(theta)	

f = 2*x

b = fct(f,N)

plt.plot(x,np.transpose(chebval(x,b)),'.g')
plt.plot(x,f)